name: Build docker base image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower."
        required: true
        type: string

permissions:
  contents: read

jobs:
  parameters:
    name: Collect build parameters
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      pip-version: ${{ steps.versions.outputs.pip-version }}
      setuptools-version: ${{ steps.versions.outputs.setuptools-version }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ./.github/actions/bootstrap
        id: bootstrap

      - id: versions
        run: |
          echo "pip-version=${{ steps.bootstrap.outputs.pip-version }}" >> "$GITHUB_OUTPUT"
          echo "setuptools-version=${{ steps.bootstrap.outputs.setuptools-version }}" >> "$GITHUB_OUTPUT"

  build-base-images:
    name: Build base images
    uses: ./.github/workflows/_docker-build.yml
    needs: parameters
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        distro:
          - name: ubuntu
            version: "22.04"
          - name: alpine
            version: "3.19"
    with:
      namespace-repository: flwr/base
      file-dir: src/docker/base/${{ matrix.distro.name }}
      build-args: |
        PYTHON_VERSION=${{ matrix.python-version }}
        PIP_VERSION=${{ needs.parameters.outputs.pip-version }}
        SETUPTOOLS_VERSION=${{ needs.parameters.outputs.setuptools-version }}
        DISTRO=${{ matrix.distro.name }}
        DISTRO_VERSION=${{ matrix.distro.version }}
        FLWR_VERSION=${{ github.event.inputs.flwr-version }}
      tags: ${{ github.event.inputs.flwr-version }}-py${{ matrix.python-version }}-${{ matrix.distro.name }}${{ matrix.distro.version }}
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
